### ISSUE TITLE
Mention when names used on the wiki are unofficial in context notes

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-data#22]
...Context notes are only sorta kinda implemented right now, so it's basically blocked on that, but we should make it clear when the name used for a track never actually came from its artist. Thanks to Niklink for the suggestion (via Discord):

> figure out how to deal with tracks that have invented or modified names dating from the original sound test (currently: aradia's theme pre-death, a baby legend - the baby is two, jadesprite, rex english)

**Comment by Niklink** [comment]
Adding context!

In the original credits doc for the Homestuck Sound Test, I'd note when I had taken it into my own hands to name a track. This happened quite often as WIPs were shared with no identifiers or music was featured in the comic with no comment. I had two 'tiers' for this: whether the title for a track was suggested by the context it which it was shared (posted alongside an image, something written in the post tags, used in the comic in a certain place, etc) or whether it was more or less completely made up.

## Unreleased Tracks

### [Problem Sleuth Theme](https://wheals.github.io/newsposts/newsposts.html#4/07/09b)

The song was never given a proper name in the newspost that mentions it as a "theme for Problem Sleuth". Later Sound Test versions list it as "Problem Sleuth Title Theme". The original filename is `ProblemSleuth.mp3` and it is in fact still hosted on the same URL of Hadley's site: http://www.parsecproductions.net/music/ProblemSleuth.mp3 Rating: Suggested.

### Windchime Foley

I didn't include this in my early versions of the Sound Test. The [MSPA Sound Credits page](http://www.mspaintadventures.com/soundcredits.html) lists it as 'Sound effects', and later on 'Foley', not like a title or anything, because it literally is a foley. Newer Sound Test versions include the track as 'Foley' as well. nsnd lists it as 'Wind chime foley'.

### Flute Performance

Originally listed in the credits as being named 'Flute Refrain'. Later credits doesn't give it a name, just 'Flute performed by'.

### SBAHJ THE MOVIE 1

Older credits DO list this and list it as 'Sweet Bro Theme Song'
Rating: Suggested. Probably because it was featured *in* `SBAHJthemovie1.swf`.

### Nic Cage Romance

Rating: Suggested. Older credits list it as 'two shitty nic cage songs' alongside what would later be released as 'Nic Cage Song'.

### Typheus / Typheus (Glitched)

Rating: Made up! This track thrice plays as ambient noise in situations related to Typheus. We don't even know the composer. Probably Toby?

### [Flare (Cascade)](https://plazmataz.tumblr.com/post/19774190658/download-flare-cascade-i-have-recut-and) / Savior of the Dreaming Dead (Cascade Cut)

So here's the thing. Right after Cascade released, Plazmataz shared the Cascade version of Flare as "Flare (Cascade Cut)". It just has the cascade ending section, minus Dreaming Dead fading in at the end, so you hear it fade out properly. That's what the name of "Savior of the Dreaming Dead (Cascade Cut)" is based off (it's just lifted directly from the Flash file, I don't think it was ever released by any other means). Then several months later she released it as "Flare (Cascade)", completed with a wholly new section to wind the song down after the climax. [You can see both versions were side by side on her Tindeck account.](https://web.archive.org/web/20120419044947/http://tindeck.com/users/Plasma) Both of these versions have some differences between themselves and between the audio as it appears in Cascade itself with regards to the old Flare sections that are included.

I'm listing this here because I have no idea why these two tracks are in More Homestuck Fandom where they obviously don't belong.

### Goat Foley

I used to have it as "Sick Bleats" on the old Sound Tests, as it remains to this day. Rating: Official name (!!! Possibly forgot to note?). Listed as simply "Foley" on MSPA. Could use investigating.

UPDATE: Older versions of the credits page do in fact list it as being named 'Sick Bleats'.

### Trickster Mode (Engage / Blast Off)

Listed simply as "Trickster Mode" on MSPA, even though they're pretty clearly two different songs. I'd stuck them together as one track, later Sound Tests have them as "Trickster Mode" and "Trickster Mode 2"

### A Very Trickster Mode Christmas

Listed on my original Sound Tests as "ZLLYSANTAKIND" (combining both versions) with a Made Up rating. Not listed on MSPA. Listed on nsnd as "Trickster Mode (3)".

### Warhammer of Zillyhoo (With Mario Paint)

Name comes from later Sound Tests, which also credits it to... Bowman/Hussie? Not sure about this. It's not listed on MSPA.

### Yaldabaoth

Rating: Made up! My original credits it to Toby instead of it being unknown! It's probably true!

### Echidna

Rating: Suggested.

## More Homestuck Fandom

### [A Baby Legend - The Baby is 2](https://web.archive.org/web/20130312050613/http://fwugradiation.tumblr.com/tagged/the-baby-is-you)

I can't recall the picture shared alongside the song at all. Post says it was drawn by mia/astroliner, who also did the album artwork for the original album. Image filename is `why_is_she_alive.PNG`. As for the song name, notably the name of the track itself is ONLY 'A Baby Legend', as it was supposed to be part of the never-made 'The Baby is 2' sequel album. However it's gone so long under that name, and no other 'The Baby is 2' media was ever publicly shared to my knowledge, I think it's perfectly fair to keep the song title that way without declaring it unofficial.

In the original Sound Test credits doc I did not note this track's name as being unofficial in any way.

### [Rex English](https://web.archive.org/web/20111110134032/http://fwugradiation.tumblr.com:80/post/12287015978)

As you can see it was just shared with a picture and tag of Lord English. I think the name I came up with for it is quite nice and straight to the point if I do say so myself, since the track is basically just RDA and English mashed together. Rating: Suggested

### Jadesprite

Rating: Suggested. I can't find Toby's tumblr post for Jadesprite but I remember very clearly it was shared along with the same image I used for the track art (back then I put track art on the songs, usually just screenshots from the comic) of Jadesprite meeting Davesprite in late A5A2: 
![Jadesprite](https://user-images.githubusercontent.com/25875275/204109728-da44baaa-7fa9-4b64-8631-3211a47c5b71.png)

### Aradia's Theme Pre-Death

Rating: Suggested. I don't recall or can find Toby's tumblr post for this song, but it PROBABLY was shared with the same picture I used for the track art (he did that often, sharing WIP tracks with just an accompanying picture),

![Aradia's Theme Pre-Death](https://user-images.githubusercontent.com/25875275/204109706-f452638a-2ca3-4868-a44b-98e89c468a86.png)
