### ISSUE TITLE
Additional files & possible new wallpaper for Symphony Impossible to Play

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-data#37]
Check out the Tumblr post from Tavia Morra! https://seeyoutmorra.tumblr.com/post/105491297899/symphony-impossible-to-play-by-clark-powell-cover

See my Discord commentary:

> oh these are slick - they totally count as Additional Files and like, we *could* use one of them as the wallpaper if you want (replacing the current general solo month bg). even though they werent *included* with the album, they still fall under the "additional files" feature imo—we can just take note in the description that they were released separately on tumblr (with a source link)

Thanks for the catch, Niklink!

**Comment by Niklink** [comment]
For reference the issue is that tumblr is serving compressed versions of the images and while there *used* to be a way to access the source uploaded file it seems to have been changed at some point so that you just can't.

There's also this post: https://seeyoutmorra.tumblr.com/post/29379923304/well-hello-hello-theres-been-a-demand-for

But the files it links to on Tavia's site are dead now too D:

**Comment by Niklink** [comment]
For future reference, the only way I could find to obtain raw, as-uploaded images off tumblr is to reblog the posts with the images you want and then export your whole blog. But it works, dammit!
