### ISSUE TITLE
Add Vol. 4 wallpapers to Vol. 1-4 as additional files

### ISSUE THREAD

**Issue by Niklink** [hsmusic/hsmusic-data#96]
Vol. 1-4 also included the SBURB wallpapers in its download. It might sound a little silly to double up on additional files like that but part of the intent is to also give information on what material was included with each album download, so I think it's probably fair game.

**Comment by towerofnix** [comment]
Agreed on fair game :P

Also just to contextualize my opinion, I'm keeping this in post-release (unlike https://github.com/hsmusic/hsmusic-data/issues/103#issuecomment-1384628478) because it's to do with content that is already on the wiki (the SBURB wallpapers), which make sense to be included as details in Vol. 1-4 under the current scope of what goes in additional files (<- includes all stuff part of the album download). <sub>Key words "already on the wiki" and "current scope". ^_^</sub>
